#!/bin/sh

case "$1" in
  start)
  	echo "loading modules"
	modprobe hello
	/etc/init.d/misc_load faulty
	/etc/init.d/scull_load scull
	;;
  stop)
	echo "unloading"
	rmmod hello
	/etc/init.d/misc_unload faulty
	/etc/init.d/scull_unload scull
	;;
esac

